repos: 
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    stages: [commit]
    types: [python]
    entry: bash -c './test.sh'
    language: system
    pass_filenames: false
    always_run: true
